language: erlang
otp_release:
       - R16B
       - R15B02
       - R15B01
       - R15B
script: "make rebuild"
branches:
        only:
                - master
                - next
notifications:
  email:
    - core@erlware.org
  irc:
    channels:
      - "irc.freenode.org#erlware"
    use_notice: true
    skip_join: true
