sudo: false
language: erlang
otp_release:
       - 18.0
       - 17.5
       - R16B
       - R15B02
       - R15B01
       - R15B
cache:
  directories:
  - $HOME/.cache/rebar3/hex/default/
install: "true" # don't let travis run get-deps
script: "./rebar3 update && ./rebar3 eunit && ./rebar3 dialyzer"
branches:
        only:
                - master
                - next
notifications:
  email:
    - core@erlware.org
  irc:
    channels:
      - "irc.freenode.org#erlware"
    use_notice: true
    skip_join: true
